app:
  name: "trades"
  env: "local"
  logLevel: "debug"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

hpa:
  enabled: true

image:
  repository: "robertgill/csv-files-reader"
  tag: "latest"
  pullPolicy: "IfNotPresent"

mysql:
  databaseName: "trades"
  user: "gocanto"
  password: "gocanto"
  host: "mysql"
  port: 3306

resources:
  requests:
    cpu: "100m"
    memory: "64Mi"
  limits:
    cpu: "500m"
    memory: "128Mi"

service:
  port: 8080
  targetPort: 8080
  type: ClusterIP

livenessProbe:
  tcpSocket:
    port: 8080
  initialDelaySeconds: 30
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  tcpSocket:
    port: 8080
  initialDelaySeconds: 20
  timeoutSeconds: 3
  periodSeconds: 5
  failureThreshold: 3

