apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  APP_NAME: "{{ .Values.app.name }}"
  APP_ENV: "{{ .Values.app.env }}"
  APP_LOG_LEVEL: "{{ .Values.app.logLevel }}"
  APP_HTTP_SERVING_PORT: "{{ .Values.service.targetPort }}"
  MYSQL_DATABASE_NAME: "{{ .Values.mysql.databaseName }}"
  MYSQL_USER: "{{ .Values.mysql.user }}"
  MYSQL_HOST: "{{ .Values.mysql.host }}"
  MYSQL_PORT: "{{ .Values.mysql.port }}"

