autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

hpa:
  enabled: true

image:
  repository: "mysql"
  tag: "8.3.0"
  pullPolicy: "IfNotPresent"

initdb:
  scripts:
    enabled: true
    sqlScript: |
      CREATE TABLE IF NOT EXISTS trades (
          id INT AUTO_INCREMENT PRIMARY KEY,
          unix VARCHAR(255) NOT NULL,
          symbol VARCHAR(255) NOT NULL,
          `open` FLOAT NOT NULL,
          high FLOAT NOT NULL,
          low FLOAT NOT NULL,
          `close` FLOAT NOT NULL
      );

mysql:
  rootPassword: "secret"
  databaseName: "trades"
  user: "gocanto"
  password: "gocanto"

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 8Gi

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

service:
  port: 3306
  type: ClusterIP

livenessProbe:
  exec:
    command:
      - "mysqladmin"
      - "-uroot"
      - "-p$MYSQL_ROOT_PASSWORD"
      - "ping"
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5

readinessProbe:
  exec:
    command:
      - /bin/sh
      - -ec
      - set -ex
      - >-
        mysql -h127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD -e'SELECT 1'
  initialDelaySeconds: 20
  periodSeconds: 5
  timeoutSeconds: 3

